import type { DesignItem, FeedMeta, SourceStatus } from './feed-types'

// Generated by scripts/fetch-feed.mjs. Do not edit by hand.
export const feedMeta: FeedMeta = {
  "fetchedAt": "2026-07-18T14:36:11.151Z",
  "fetchedAtLabel": "2026.07.18 22:36 CST",
  "activeSourceCount": 2,
  "newItemCount": 6,
  "note": "页面展示最近一次成功同步的公开数据快照。"
}

export const sourceStatus: SourceStatus[] = [
  {
    "name": "The FWA",
    "state": "同步失败，保留快照",
    "method": "公开首页",
    "tone": "blue",
    "url": "https://thefwa.com/",
    "active": false
  },
  {
    "name": "CSS Nectar",
    "state": "已接入",
    "method": "公开 RSS",
    "tone": "ink",
    "url": "https://cssnectar.com/",
    "active": true
  },
  {
    "name": "CSS Design Awards",
    "state": "同步失败，保留快照",
    "method": "公开获奖与提名页",
    "tone": "lime",
    "url": "https://www.cssdesignawards.com/",
    "active": false
  },
  {
    "name": "CSS Winner",
    "state": "已接入",
    "method": "公开获奖页",
    "tone": "coral",
    "url": "https://www.csswinner.com/winners",
    "active": true
  }
]

export const items: DesignItem[] = [
  {
    "id": "css-winner-19308",
    "title": "Why Zero",
    "date": "2026-07-18",
    "url": "https://www.csswinner.com/details/why-zero/19308",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/539630503.jpg",
    "sourceUrl": "https://www.csswinner.com/details/why-zero/19308",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 18 日",
    "fresh": true
  },
  {
    "id": "css-winner-19309",
    "title": "Shaky Gotcha",
    "date": "2026-07-17",
    "url": "https://www.csswinner.com/details/shaky-gotcha/19309",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/780698349.jpg",
    "sourceUrl": "https://www.csswinner.com/details/shaky-gotcha/19309",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 17 日",
    "fresh": true
  },
  {
    "id": "css-winner-19303",
    "title": "RISK",
    "date": "2026-07-16",
    "url": "https://www.csswinner.com/details/risk/19303",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1723473746.jpg",
    "sourceUrl": "https://www.csswinner.com/details/risk/19303",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "7 月 16 日",
    "fresh": true
  },
  {
    "id": "css-winner-19301",
    "title": "PLANETOOOTE — A Digital Obsession",
    "date": "2026-07-15",
    "url": "https://www.csswinner.com/details/planetooote-a-digital-obsession/19301",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/199042332.jpg",
    "sourceUrl": "https://www.csswinner.com/details/planetooote-a-digital-obsession/19301",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 15 日",
    "fresh": true
  },
  {
    "id": "css-winner-19300",
    "title": "evian Gallery of Youth",
    "date": "2026-07-14",
    "url": "https://www.csswinner.com/details/evian-gallery-of-youth/19300",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1650956510.jpg",
    "sourceUrl": "https://www.csswinner.com/details/evian-gallery-of-youth/19300",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 14 日",
    "fresh": true
  },
  {
    "id": "css-winner-19299",
    "title": "[PORTFOLIO]",
    "date": "2026-07-13",
    "url": "https://www.csswinner.com/details/portfolio/19299",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1954709733.jpg",
    "sourceUrl": "https://www.csswinner.com/details/portfolio/19299",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "7 月 13 日",
    "fresh": true
  },
  {
    "id": "css-nectar-https%3A%2F%2Fcssnectar.com%2Fjavascript%2F75-css-animation-examples%2F",
    "title": "75+ CSS Animation Examples",
    "date": "2024-02-19",
    "url": "https://cssnectar.com/javascript/75-css-animation-examples/",
    "image": "https://cssnectar.com/wp-content/uploads/2024/02/Recording-2024-02-19-120851.mp4",
    "sourceUrl": "https://cssnectar.com/javascript/75-css-animation-examples/",
    "source": "CSS Nectar",
    "channel": "精选网站",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "2 月 19 日",
    "fresh": false
  }
]
