import type { DesignItem, FeedMeta, SourceStatus } from './feed-types'

// Generated by scripts/fetch-feed.mjs. Do not edit by hand.
export const feedMeta: FeedMeta = {
  "fetchedAt": "2026-07-18T12:27:37.598Z",
  "fetchedAtLabel": "2026.07.18 20:27 CST",
  "activeSourceCount": 1,
  "newItemCount": 1,
  "note": "页面展示最近一次成功同步的公开数据快照。"
}

export const sourceStatus: SourceStatus[] = [
  {
    "name": "The FWA",
    "state": "同步失败，保留快照",
    "method": "公开首页",
    "tone": "blue",
    "url": "https://thefwa.com/",
    "active": false
  },
  {
    "name": "CSS Nectar",
    "state": "已接入",
    "method": "公开 RSS",
    "tone": "ink",
    "url": "https://cssnectar.com/",
    "active": true
  }
]

export const items: DesignItem[] = [
  {
    "id": "css-nectar-https%3A%2F%2Fcssnectar.com%2Fjavascript%2F75-css-animation-examples%2F",
    "title": "75+ CSS Animation Examples",
    "date": "2024-02-19",
    "url": "https://cssnectar.com/javascript/75-css-animation-examples/",
    "image": "https://cssnectar.com/wp-content/uploads/2024/02/Recording-2024-02-19-120851.mp4",
    "sourceUrl": "https://cssnectar.com/javascript/75-css-animation-examples/",
    "source": "CSS Nectar",
    "channel": "精选网站",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "2 月 19 日",
    "fresh": true
  }
]
