import type { DesignItem, FeedMeta, SourceStatus } from './feed-types'

// Generated by scripts/fetch-feed.mjs. Do not edit by hand.
export const feedMeta: FeedMeta = {
  "fetchedAt": "2026-07-19T04:36:40.468Z",
  "fetchedAtLabel": "2026.07.19 12:36 CST",
  "activeSourceCount": 3,
  "newItemCount": 6,
  "note": "页面展示最近一次成功同步的公开数据快照。"
}

export const sourceStatus: SourceStatus[] = [
  {
    "name": "The FWA",
    "state": "同步失败，保留快照",
    "method": "公开首页",
    "tone": "blue",
    "url": "https://thefwa.com/",
    "active": false
  },
  {
    "name": "CSS Nectar",
    "state": "已接入",
    "method": "公开 RSS",
    "tone": "ink",
    "url": "https://cssnectar.com/",
    "active": true
  },
  {
    "name": "CSS Design Awards",
    "state": "已接入",
    "method": "公开获奖与提名页",
    "tone": "lime",
    "url": "https://www.cssdesignawards.com/",
    "active": true
  },
  {
    "name": "CSS Winner",
    "state": "已接入",
    "method": "公开获奖页",
    "tone": "coral",
    "url": "https://www.csswinner.com/winners",
    "active": true
  }
]

export const items: DesignItem[] = [
  {
    "id": "cssda-49814",
    "title": "Orgnzm Studio",
    "date": "2026-07-18",
    "url": "https://www.cssdesignawards.com/sites/orgnzm-studio/49814/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202607/20260718051921.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/orgnzm-studio/49814/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "wide",
    "dateLabel": "7 月 18 日",
    "fresh": true
  },
  {
    "id": "cssda-49816",
    "title": "Rechroma",
    "date": "2026-07-18",
    "url": "https://www.cssdesignawards.com/sites/rechroma/49816/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202607/20260718051938.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/rechroma/49816/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "portrait",
    "dateLabel": "7 月 18 日",
    "fresh": true
  },
  {
    "id": "css-winner-19308",
    "title": "Why Zero",
    "date": "2026-07-18",
    "url": "https://www.csswinner.com/details/why-zero/19308",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/539630503.jpg",
    "sourceUrl": "https://www.csswinner.com/details/why-zero/19308",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 18 日",
    "fresh": false
  },
  {
    "id": "cssda-49680",
    "title": "The Watch",
    "date": "2026-07-17",
    "url": "https://www.cssdesignawards.com/sites/the-watch/49680/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202606/20260627032443.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/the-watch/49680/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "wide",
    "dateLabel": "7 月 17 日",
    "fresh": true
  },
  {
    "id": "css-winner-19309",
    "title": "Shaky Gotcha",
    "date": "2026-07-17",
    "url": "https://www.csswinner.com/details/shaky-gotcha/19309",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/780698349.jpg",
    "sourceUrl": "https://www.csswinner.com/details/shaky-gotcha/19309",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 17 日",
    "fresh": false
  },
  {
    "id": "cssda-49651",
    "title": "Le Mans Classic",
    "date": "2026-07-16",
    "url": "https://www.cssdesignawards.com/sites/le-mans-classic/49651/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202606/20260624063614.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/le-mans-classic/49651/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "portrait",
    "dateLabel": "7 月 16 日",
    "fresh": true
  },
  {
    "id": "css-winner-19303",
    "title": "RISK",
    "date": "2026-07-16",
    "url": "https://www.csswinner.com/details/risk/19303",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1723473746.jpg",
    "sourceUrl": "https://www.csswinner.com/details/risk/19303",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "7 月 16 日",
    "fresh": false
  },
  {
    "id": "cssda-49616",
    "title": "Dmitry Glukhovsky — Portfolio",
    "date": "2026-07-15",
    "url": "https://www.cssdesignawards.com/sites/dmitry-glukhovsky/49616/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202606/20260619065938.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/dmitry-glukhovsky/49616/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "wide",
    "dateLabel": "7 月 15 日",
    "fresh": true
  },
  {
    "id": "css-winner-19301",
    "title": "PLANETOOOTE — A Digital Obsession",
    "date": "2026-07-15",
    "url": "https://www.csswinner.com/details/planetooote-a-digital-obsession/19301",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/199042332.jpg",
    "sourceUrl": "https://www.csswinner.com/details/planetooote-a-digital-obsession/19301",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 15 日",
    "fresh": false
  },
  {
    "id": "cssda-49617",
    "title": "Get Blue",
    "date": "2026-07-14",
    "url": "https://www.cssdesignawards.com/sites/get-blue/49617/",
    "image": "https://www.cssdesignawards.com/cdasites/2026/202606/20260619065929.jpg",
    "sourceUrl": "https://www.cssdesignawards.com/sites/get-blue/49617/",
    "source": "CSS Design Awards",
    "channel": "设计奖项",
    "accent": "#809546",
    "aspect": "wide",
    "dateLabel": "7 月 14 日",
    "fresh": true
  },
  {
    "id": "css-winner-19300",
    "title": "evian Gallery of Youth",
    "date": "2026-07-14",
    "url": "https://www.csswinner.com/details/evian-gallery-of-youth/19300",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1650956510.jpg",
    "sourceUrl": "https://www.csswinner.com/details/evian-gallery-of-youth/19300",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "wide",
    "dateLabel": "7 月 14 日",
    "fresh": false
  },
  {
    "id": "css-winner-19299",
    "title": "[PORTFOLIO]",
    "date": "2026-07-13",
    "url": "https://www.csswinner.com/details/portfolio/19299",
    "image": "https://cdn.csswinner.com/images/winners/2026/jul/1954709733.jpg",
    "sourceUrl": "https://www.csswinner.com/details/portfolio/19299",
    "source": "CSS Winner",
    "channel": "设计奖项",
    "accent": "#d96b51",
    "aspect": "square",
    "dateLabel": "7 月 13 日",
    "fresh": false
  }
]
